# Generated by Django 2.2.5 on 2020-02-14 17:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, upload_to='carrusel')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Carrusel',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('imagen', models.ImageField(blank=True, upload_to='categorias')),
                ('descripcion', models.TextField(blank=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nombre')),
                ('imagen', models.ImageField(blank=True, upload_to='productos')),
                ('marca', models.CharField(blank=True, max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
