# Generated by Django 3.0.3 on 2020-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, upload_to='carrusel')),
            ],
            options={
                'verbose_name_plural': 'Carrusel',
            },
        ),
    ]
