# Generated by Django 2.2.5 on 2020-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='nombreclass',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
